### ISSUE TITLE
Return empty result after cloning db and files from live to dev

### ISSUE THREAD

**Issue by fusionx1** [pantheon-systems/terminus-secrets-plugin#17]
Step to reproduce:
1. Have different versions of secrets.json on live and dev.
2. Ensure you can read the secrets of dev via the terminus plugin.
3. Clone database and files from live to dev.
4. Trying to read secrets via the terminus plugin but fails and return an empty result
5. You can fix the issue by SFTPing into dev and overwriting the
secrets.json file with anything that has valid json. After this, you will be able to read secrets.json again via terminus.

Result:
https://screencast.com/t/qAoHvpRX7

I didn't get any errors but I'm not sure yet if the empty results when running the secrets.js
could be related to the bug filed by Nicolas Bowers - https://github.com/pantheon-systems/terminus-secrets-plugin/issues/10. Updating it via sftp indeed fixed the problem. Something in the file not being read by quicksilver.

**Comment by sugaroverflow** [comment]
Closing because this was solved with #18  thanks!
