### ISSUE TITLE
Could this be used to inject config into Drupal?

### ISSUE THREAD

**Issue by eeeschwartz** [pantheon-systems/terminus-secrets-plugin#4]
**A Drupal 8 example problem**

Say I want to keep the [SMTP Authentication](https://www.drupal.org/project/smtp) config out of the database to make sure that database dumps do not copy credentials around. (Using Quicksilver to sanitize is good, but still leaves the case of direct DB access). I know that Lockr + the [key module](https://www.drupal.org/project/key) is the _best_ approach, but SMTP and many other modules do not support it yet unfortunately.

What if the `sites/default/settings.php` were to parse the secrets.json for entries like:

```
{ "drupal_settings": 
    { "smtp.settings": 
        { "smtp_username": "foo", ... }}}
```

Does this sound like a reasonable way to contain Drupal config to a given Pantheon environment? Am I missing an easier way to do this that is already available?

**Comment by stevector** [comment]
Yes, I think that is a reasonable approach. I suggest the same thing in https://pantheon.io/blog/running-drupal-8-data-migrations-pantheon-through-drush
