### ISSUE TITLE
"Not found" error when running with 0.13.3

### ISSUE THREAD

**Issue by gchaix** [pantheon-systems/terminus-secrets-plugin#5]
Running 0.13.3 on OS X (installed via Homebrew).  `terminus secrets show` throws a fatal error:

```PHP Fatal error:  Uncaught Error: Class 'Terminus\Models\Collections\Sites' not found in /Users/gchaix/terminus/plugins/terminus-secrets-plugin/Commands/SecretsCommand.php:33```

Changing line 10 of SecretsCommand.php from `use Terminus\Models\Collections\Sites;` to `use Terminus\Collections\Sites;` resolves the issue.

**Comment by greg-1-anderson** [comment]
Fixed in the latest 0.x branch.

n.b. Do not use `master` any longer. The Terminus 0.x version is on the `0.x` branch, and the 1.x version is on the `1.x` branch.  The `master` branch will be deleted shortly.
